<h4>界面介绍</h4>
<p>工作区由从左至右分为两部分：管理员列表和权限明细</p>
<p>管理员列表：显示所有管理员信息</p>
<p>权限明细：显示当前选中管理员的权限明细,<input type="checkbox" checked />表示具有某种权限</p>

<h4>添加管理员</h4>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-add'">添加</a>按钮,将在管理员表格中增加一个空白行</p>
<p>输入管理员基本信息</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>

<h4>删除管理员</h4>
<p>单击表格行左边的复选框选中一行（可多选）,再单击<a class="easyui-linkbutton" data-options="iconCls:'icon-remove'">删除</a>按钮</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>

<h4>修改管理员</h4>
<p>双击列表中的一行，编辑要修改的列的信息</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>

<h4>修改权限</h4>
<p>可以根据实际工作需要给不同的管理员赋予不同的权限</p>
<p>通过单击权限前的复选框赋予或撤销某项权限</p>
<p><a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存权限</a></p>

<h4>操作反馈</h4>
<p>预订或者退订操作都会有执行结果反馈</p>
<p>反馈消息出现在窗口右下角，持续显示10秒后自动消失，也可直接关闭</p>
<p>如果需要更长时间查看反馈结果，可以通过鼠标单击来激活该提示窗口</p>
