<h4>查询送餐单</h4>
<p>选择送餐线路</p>
<p>选择送餐日期，默认当天的送餐统计</p>
<p>选择套餐类型，13:00以后默认选择晚餐；20:00以后默认选择零点送餐；其它选择中餐</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-search'">查询</a></p>

<h4>显示送菜单</h4>
<p>按照指定线路的送餐点顺序显示每个送餐点每个班组的订餐分数统计</p>
<p>如果是零点餐会在备注中显示A餐、B餐、C餐的份数</p>
<p>汇总栏除了显示总数，还会显示按食堂统计的分数，便于取餐</p>

<h4>导出送菜单</h4>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-xls'">导出</a>可以将送菜单保存到Excel中，前提是该电脑安装有Excel并降低浏览器的安全模式</p>
<h4>打印送菜单</h4>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-print'">打印</a>可以直接打印送餐单</p>
