<h4>查询职工</h4>
<p>可按照公司、车间、班组、角色、工号或姓名来查询，也可以按照它们的组合条件查询</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-search'">查询</a></p>

<h4>添加职工</h4>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-add'">添加</a>按钮,将在职工表格中增加一个空白行</p>
<p>输入职工基本信息</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>

<h4>删除职工</h4>
<p>单击表格行左边的复选框选中一行（可多选）</p>
<p>再单击<a class="easyui-linkbutton" data-options="iconCls:'icon-remove'">删除</a>按钮</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>

<h4>修改职工</h4>
<p>双击列表中的一行，编辑要修改的列的信息</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>

<h4>调岗</h4>
<p>单击表格行左边的复选框选中一行（可多选）</p>
<p>选择调岗的目标车间和班组</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-exchange'">调岗至</a></p>

<h4>批量保存和撤销</h4>
<p>可以在执行多个添加、删除、修改等操作后批量保存</p>
<p>可单击<a class="easyui-linkbutton" data-options="iconCls:'icon-undo'">撤销</a>按钮撤销所有未保存的操作</p>

<h4>操作反馈</h4>
<p>保存操作会有执行结果反馈</p>
<p>反馈消息出现在窗口右下角，持续显示3~10秒后自动消失，也可直接关闭</p>
<p>如果需要更长时间查看反馈结果，可以通过鼠标单击来激活该提示窗口</p>