<h4>节日的含义</h4>
<p>系统可以指定某天的某一餐执行假日价格</p>
<p>具体价格参考“套餐价格”功能</p>
<p>“例外”的公司不受此影响</p>

<h4>添加节日</h4>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-add'">添加</a>按钮,将在节日表格中增加一个空白行</p>
<p>填写节日的日期,中餐是否是节日价格,是就勾选,否则不勾选。晚餐和零点餐操类似.</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>
<h4>添加节日</h4>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-add'">添加</a>按钮,将在节日表格中增加一个空白行</p>
<p>输入节日基本信息</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>

<h4>删除节日</h4>
<p>单击表格行左边的复选框选中一行（可多选）,再单击<a class="easyui-linkbutton" data-options="iconCls:'icon-remove'">删除</a>按钮</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>

<h4>修改节日</h4>
<p>双击列表中的一行，编辑要修改的列的信息</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a></p>

<h4>批量保存和撤销</h4>
<p>可以在执行多个添加、删除、修改等操作后批量保存</p>
<p>可单击<a class="easyui-linkbutton" data-options="iconCls:'icon-undo'">撤销</a>按钮撤销所有未保存的操作</p>

<h4>操作反馈</h4>
<p>保存操作会有执行结果反馈</p>
<p>反馈消息出现在窗口右下角，持续显示3~10秒后自动消失，也可直接关闭</p>
<p>如果需要更长时间查看反馈结果，可以通过鼠标单击来激活该提示窗口</p>