
<h4>添加公告</h4>
<p>先单击工具栏的<a class="easyui-linkbutton" data-options="iconCls:'icon-add'">添加</a>按钮,会在弹出一个编辑框</p>
<p>填写公告的标题、内容、发布日期（默认为当前日期）.</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-exchange'">确定</a></p>

<h4>删除公告</h4>
<p>选中一行,再单击工具栏的<a class="easyui-linkbutton" data-options="iconCls:'icon-remove'">删除</a>按钮</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-exchange'">确定</a></p>

<h4>修改公告</h4>
<p>双击列表中的一行，编辑要修改的列的信息</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-exchange'">确定</a></p>


<h4>操作反馈</h4>
<p>预订或者退订操作都会有执行结果反馈</p>
<p>反馈消息出现在窗口右下角，持续显示10秒后自动消失，也可直接关闭</p>
<p>如果需要更长时间查看反馈结果，可以通过鼠标单击来激活该提示窗口</p>
