
<h4>价格说明</h4>
<p>价格具有时限，在指定的范围内有效，其日期范围不允许重叠</p>
<p>价格具有类别，有中、晚、零点餐以及日常、假日、例外之分，例外价格指的是有些公司按照例外的价格执行，没有日常和假日价格之分</p>

<h4>添加价格</h4>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-add'">添加</a>即可在价格列表中添加一条价格，并进入编辑模式</p>
<p>选择起止日期和输入各种套餐价格</p>
<p>注意如果日期范围与现有的价格日期范围有重叠，则不允许添加</p>

<h4>删除价格</h4>
<p>选中一个或多个价格</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-remove'">删除</a></p>

<h4>修改价格</h4>
<p>双击价格，即可进入编辑模式修改</p>

<h4>保存价格</h4>
<p>所有增、删、改操作只有单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'" >保存</a>才能正式生效，未生效的可以通过单击<a class="easyui-linkbutton" data-options="iconCls:'icon-undo'" >撤销</a>予以撤销</p>
