
<h4>用餐点列表显示</h4>
<p>左边显示【职工可选用餐点】</p>
<p>右边显示【全部用餐点】</p>

<h4>用餐点编辑</h4>
<p>选择【全部用餐点】中的用餐点，然后单击<a class="easyui-linkbutton" data-options="iconCls:'icon-back'">添加</a>即可将其加入【职工可选用餐点】</p>
<p>第一个用餐点即为默认用餐点</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-move_up'">上移</a><a class="easyui-linkbutton" data-options="iconCls:'icon-move_down'"">下移</a>可调整顺序</p>
<p>单击<a class="easyui-linkbutton" data-options="iconCls:'icon-remove'">删除</a>将所选用餐点用【职工可选用餐点】中删除</p>
<p>所有编辑操作只有单击<a class="easyui-linkbutton" data-options="iconCls:'icon-save'">保存</a>才能生效</p>