<h4>修改角色</h4>
<p>车间管理员可以修改员工的角色，选择车间成员后点击<a class="easyui-linkbutton" data-options="iconCls:'icon-edit'">设为班组管理员</a>后将员工设置为班组管理员<a class="easyui-linkbutton" data-options="iconCls:'icon-edit'">设为普通职工</a>后将员工设置为普通职工</p>
<h4>调岗</h4>
<p>车间管理员可以将车间内部人员进行调岗，选择将要跳到的班组后单击<a class="easyui-linkbutton" data-options="iconCls:'icon-exchange'">调岗至</a>就可以将员工调到对应的班组</p>
<h4>车间基本信息</h4>
<p>车间名、电话显示在顶部</p>

<h4>车间显示</h4>
<p>显示车间或班组所有成员的基本信息、送餐点和套餐剩余数</p>
<p>车间管理员可以按照班组进行过滤</p>
<p>单击送餐点后面的<a href="#" >编辑</a>可以编辑职工的可选用餐点</p>
